Homelab: Full architecture redesign (#486)
Complete redesign of my Homelab to switch to a much simpler,
lightweight, secure and resource efficient architecture design:

- Replace Proxmox on physical hosts by a lightweight Arch Linux install
that only runs basic services like `sshd`, `firewalld`, `fail2ban`,
etc..., as well as rootless LXC & Podman (see next points) [1].
- Replace VMs by rootless / unprivileged LXC System containers (acting
"VM-Like", with dedicated hostname, IP, resources quota limit, direct
SSH access, etc...).
- Replace Docker by rootless / unprivileged Podman Application
containers.
- Application containers (Podman) run directly on the physical hosts
(rather than in dedicated VMs as before).
- Tasks initially managed via Proxmox (snapshots, backups, etc...) are
handled via Ansible (in addition of the "classic" administration tasks,
system & containers updates, etc...). The Ansible architecture is also
reworked / simplified.
- Every rootless / unprivileged containers are all executed via a
dedicated & unprivileged user, with secured login mechanisms (no ssh
access, no password authentication, no `su - user`, etc... only `sudo
-iu user` / `sudo machinectl shell user@` from another *privileged*
user).
- Day to day administration tasks, log viewing, etc... are done from a
separate / classic user.
- HA for critical services is managed on the software side by running
clusters with the different nodes (LXC Containers) spared across the
different physical hosts and a floating VIP managed at the service-level
by `keepalived`.

This should result in a much simpler, pragmatic, secure & resource
efficient architecture design overall; though at the cost of handy /
"QOL" features such has the centralized Proxmox WebUI, one click
snapshot / backups, built-in HA fencing, live-migration, etc...

However, some of those handy features can (and will) be replaced by
custom scripting / Ansible playbooks (e.g. for snapshots / backups). VMs
are a bit more flexible and have a better isolation by design, but they
are also more complex and way less resource efficient than containers.
As for other stuff like HA fencing, live-migration and so on... while
they are handy, they also imply more or less technical overhead. For
instance, I need to run a third quorum node from a RaspberryPI to get
proper HA from Proxmox, CEPHS storage is resource intensive, cluster
management may complicate things in specific situation (e.g. when
upgrading / reinstalling nodes to a new major version), etc... And it's
fair to say that I don't really *need* those things for my Homelab.

All and all, this is treading (some) convenience for simplicity
(architecture wise), with everything it implies: lighter on resources,
less attack surfaces, lighter maintenance, ... at the cost of loosing
certain extra features or having to rely on custom solutions for those.
It also a fun experiment that I'm looking forward to try.

I *might* write a blog post with my feedback about this change after
some times. 🙂

[1] I was initially considering Alpine Linux instead at first, which
felt like the perfect candidate for such tiny / "appliance like"
servers. But, unfortunately, it turns out that I won't be able to
properly run everything I want / need, mostly due to lack of systemd
ecosystem support. For instance, `podman auto-update` hardly requires
the containers to run from systemd services. I also haven't been able to
start / run Arch Linux (or any distribution running systemd >= v258,
which therefore strictly requires cgroups v2) in LXC unprivileged
containers, presumably because `OpenRC` doesn't handle cgroups
delegation, which is a deal breaker for me.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -15,13 +15,15 @@ jobs:
         run: actionlint -ignore 'label "CI-CD" is unknown' .github/workflows/CI.yml
 
       - name: Run codespell
-        run: codespell --enable-colors
+        run: codespell --enable-colors -L chage
 
       - name: Run mdl
         run: mdl --style .github/workflows/mdl_style.rb .
 
       - name: Run ansible-lint
-        run: ansible-lint -q --force-color --config-file .github/workflows/ansible-lint.conf --project-dir Ansible/playbooks/
+        run: ansible-lint -q --force-color
+        working-directory: Ansible
 
       - name: Run ansible-inventory
-        run: error=$( { ansible-inventory --list --yaml -i Ansible/inventories/ > /dev/null; } 2>&1 ); [ -n "${error}" ] && echo "${error}" && exit 1 || exit 0
+        run: error=$( { ansible-inventory --list --yaml > /dev/null; } 2>&1 ); [ -n "${error}" ] && echo "${error}" && exit 1 || exit 0
+        working-directory: Ansible
