Fix CI

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -21,7 +21,9 @@ jobs:
         run: mdl --style .github/workflows/mdl_style.rb .
 
       - name: Run ansible-lint
-        run: ansible-lint -q --force-color --config-file .github/workflows/ansible-lint.conf --project-dir Ansible/
+        run: ansible-lint -q --force-color
+	working-directory: Ansible
 
       - name: Run ansible-inventory
-        run: error=$( { ansible-inventory --list --yaml -i Ansible/inventory > /dev/null; } 2>&1 ); [ -n "${error}" ] && echo "${error}" && exit 1 || exit 0
+        run: error=$( { ansible-inventory --list --yaml > /dev/null; } 2>&1 ); [ -n "${error}" ] && echo "${error}" && exit 1 || exit 0
+	working-directory: Ansible
